LLAMA2:
  MODEL_PATH: ./models/llama-2-7b-chat.Q4_K_M.gguf
  MODEL_TYPE: llama

CODELLAMA:
  MODEL_PATH: ./models/codellama-7b-instruct.Q2_K.gguf
  MODEL_TYPE: llama

MISTRAL:
  MODEL_PATH: ./models/mistral-7b-instruct-v0.2.Q4_K_M.gguf
  MODEL_TYPE: mistral

MAX_NEW_TOKENS: 512
TEMPERATURE: 0.2
REPETITION_PENALTY: 1.1
CONTEXT_LENGTH: 1024

CLIP_MODEL_PATH: ./models/llava-7b/mmproj-model-f16.gguf
LLAVA_MODEL_PATH: ./models/llava-7b/ggml-model-q4_k.gguf

HOST: localhost
PORT_LLAMA2: 8201
PORT_CODELLAMA: 8202
PORT_MISTRAL: 8203
PORT_LLAVA: 8210
