dependencies:
  - python=3.10.12
  - pip=23.2.1
  - pip:
    - ctransformers==0.2.25
    - fastapi==0.103.0
    - langchain==0.0.275
    - python-dotenv==1.0.0
    - python-box==7.0.1
    - sentence-transformers==2.2.2
    - streamlit==1.26.0
    - uvicorn==0.23.2
    - wikipedia==1.4.0
